In [7]:
import numpy as np

UNIT = 3

arr = np.arange(UNIT**3)

scalar = arr[0]
vector = arr[0:UNIT]
matrix = arr[0:UNIT**2].reshape(UNIT, UNIT)
third_rank_tensor = arr.reshape(UNIT, UNIT, UNIT)

print(scalar,vector,matrix,third_rank_tensor,sep="\n\n")

0

[0 1 2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
