In [4]:
import numpy as np

a = np.array([[0, 1, 2], [1, 2, 3]])
b = np.array([[2, 1], [2, 1], [2, 1]])

print(np.dot(a, b))


[[ 6  3]
 [12  6]]


In [7]:
import numpy as np


a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b = np.array([[0, 1, 2], [2, 0, 1], [1, 2, 0]])

print(a * b)


[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [10]:
import numpy as np

a = np.array([[0, 1, 2], [1, 2, 3]])
b = np.array([[0, 1], [1, 2], [2, 3]])
print(a)
print(b)
x = np.dot(a, b)
print(x)


c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
d = np.array([[0, 2, 0], [2, 0, 2], [0, 2, 0]])
print(c)
print(d)

y = c * d
print(y)



[[0 1 2]
 [1 2 3]]
[[0 1]
 [1 2]
 [2 3]]
[[ 5  8]
 [ 8 14]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 0]
 [2 0 2]
 [0 2 0]]
[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
