In [8]:
import numpy as np

NUM_DATA = 9

a = np.empty(shape=(3, 3), dtype=int)
b = np.arange(NUM_DATA).reshape(3, 3)

for i in range(NUM_DATA):
    a.flat[i] = 2**i

print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
with np.errstate(divide='ignore'):
    print(a / b)


[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  1   3   6]
 [ 11  20  37]
 [ 70 135 264]]
[[  1   1   2]
 [  5  12  27]
 [ 58 121 248]]
[[   0    2    8]
 [  24   64  160]
 [ 384  896 2048]]
[[        inf  2.          2.        ]
 [ 2.66666667  4.          6.4       ]
 [10.66666667 18.28571429 32.        ]]
