In [2]:
import numpy as np

matrix_2 = np.eye(2)
matrix_3 = np.eye(3)
matrix_4 = np.eye(4)

print(matrix_2)
print(matrix_3)
print(matrix_4)


[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
import numpy as np


a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

b = np.array([[1, 2], [0, 0]])
print(np.linalg.det(b))


-2.0000000000000004
0.0


In [9]:
import numpy as np


a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

b = np.array([[1, 2], [0, 0]])
# print(np.linalg.inv(b))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
import numpy as np

a = np.array([[1, 1], [1, 2]])

det = np.linalg.det(a)
print(det)
print()

if det != 0:
    inv = np.linalg.inv(a)
    print(inv)


1.0

[[ 2. -1.]
 [-1.  1.]]
