In [5]:
import numpy as np

a = np.array([[0, 1, 2], [1, 2, 3]])
b = np.array([[0, 1, 2], [2, 3, 4]])

c = np.dot(a.T, b)
d = np.dot(a, b.T)
print(c)
print(d)


[[ 2  3  4]
 [ 4  7 10]
 [ 6 11 16]]
[[ 5 11]
 [ 8 20]]
